name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
         AWS_REGION: ${{ secrets.AWS_REGION }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Build, tag, and push Docker image for Patient Service
    - name: Build, Tag & Push Docker Image for helloworld
      run: |
        cd App/hello-world/
        docker build -t hackathon/helloworld .
        docker tag hackathon/helloworld:latest ${{ secrets.helloworld_ecr_url }}:latest
        docker push ${{ secrets.helloworld_ecr_url }}:latest
